# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 11:19
from __future__ import unicode_literals

import datetime
import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naturall', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gps_points',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('temprature', models.FloatField(default=20)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
